/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bmlt);
  }
}(this, function(expect, Bmlt) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bmlt.ErrorTest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ErrorTest', function() {
    it('should create an instance of ErrorTest', function() {
      // uncomment below and update the code to test ErrorTest
      //var instance = new Bmlt.ErrorTest();
      //expect(instance).to.be.a(Bmlt.ErrorTest);
    });

    it('should have the property arbitraryString (base name: "arbitrary_string")', function() {
      // uncomment below and update the code to test the property arbitraryString
      //var instance = new Bmlt.ErrorTest();
      //expect(instance).to.be();
    });

    it('should have the property arbitraryInt (base name: "arbitrary_int")', function() {
      // uncomment below and update the code to test the property arbitraryInt
      //var instance = new Bmlt.ErrorTest();
      //expect(instance).to.be();
    });

    it('should have the property forceServerError (base name: "force_server_error")', function() {
      // uncomment below and update the code to test the property forceServerError
      //var instance = new Bmlt.ErrorTest();
      //expect(instance).to.be();
    });

  });

}));
