/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bmlt);
  }
}(this, function(expect, Bmlt) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bmlt.FormatBase();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FormatBase', function() {
    it('should create an instance of FormatBase', function() {
      // uncomment below and update the code to test FormatBase
      //var instance = new Bmlt.FormatBase();
      //expect(instance).to.be.a(Bmlt.FormatBase);
    });

    it('should have the property worldId (base name: "worldId")', function() {
      // uncomment below and update the code to test the property worldId
      //var instance = new Bmlt.FormatBase();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Bmlt.FormatBase();
      //expect(instance).to.be();
    });

    it('should have the property translations (base name: "translations")', function() {
      // uncomment below and update the code to test the property translations
      //var instance = new Bmlt.FormatBase();
      //expect(instance).to.be();
    });

  });

}));
