/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bmlt);
  }
}(this, function(expect, Bmlt) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bmlt.RootServerBaseStatisticsMeetings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RootServerBaseStatisticsMeetings', function() {
    it('should create an instance of RootServerBaseStatisticsMeetings', function() {
      // uncomment below and update the code to test RootServerBaseStatisticsMeetings
      //var instance = new Bmlt.RootServerBaseStatisticsMeetings();
      //expect(instance).to.be.a(Bmlt.RootServerBaseStatisticsMeetings);
    });

    it('should have the property numTotal (base name: "numTotal")', function() {
      // uncomment below and update the code to test the property numTotal
      //var instance = new Bmlt.RootServerBaseStatisticsMeetings();
      //expect(instance).to.be();
    });

    it('should have the property numInPerson (base name: "numInPerson")', function() {
      // uncomment below and update the code to test the property numInPerson
      //var instance = new Bmlt.RootServerBaseStatisticsMeetings();
      //expect(instance).to.be();
    });

    it('should have the property numVirtual (base name: "numVirtual")', function() {
      // uncomment below and update the code to test the property numVirtual
      //var instance = new Bmlt.RootServerBaseStatisticsMeetings();
      //expect(instance).to.be();
    });

    it('should have the property numHybrid (base name: "numHybrid")', function() {
      // uncomment below and update the code to test the property numHybrid
      //var instance = new Bmlt.RootServerBaseStatisticsMeetings();
      //expect(instance).to.be();
    });

    it('should have the property numUnknown (base name: "numUnknown")', function() {
      // uncomment below and update the code to test the property numUnknown
      //var instance = new Bmlt.RootServerBaseStatisticsMeetings();
      //expect(instance).to.be();
    });

  });

}));
