/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bmlt);
  }
}(this, function(expect, Bmlt) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bmlt.ServiceBodyUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceBodyUpdate', function() {
    it('should create an instance of ServiceBodyUpdate', function() {
      // uncomment below and update the code to test ServiceBodyUpdate
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be.a(Bmlt.ServiceBodyUpdate);
    });

    it('should have the property parentId (base name: "parentId")', function() {
      // uncomment below and update the code to test the property parentId
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property adminUserId (base name: "adminUserId")', function() {
      // uncomment below and update the code to test the property adminUserId
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property assignedUserIds (base name: "assignedUserIds")', function() {
      // uncomment below and update the code to test the property assignedUserIds
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property helpline (base name: "helpline")', function() {
      // uncomment below and update the code to test the property helpline
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

    it('should have the property worldId (base name: "worldId")', function() {
      // uncomment below and update the code to test the property worldId
      //var instance = new Bmlt.ServiceBodyUpdate();
      //expect(instance).to.be();
    });

  });

}));
